spring:
  cache:
    type: none
  application:
    name: two-tier-cache-example
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    sql: debug
    org.hibernate.sql: debug
    org:
      springframework: info
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace