spring:
  application:
    name: resilience4j-example
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    #      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
logging:
  level:
    root: debug

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true  # application.yml refresh ?? ???
    health:
      show-details: always
  server:
    port: 8081  # Actuator ??? ??? port
